### ISSUE TITLE
Game crashing on Minecraft 1.20.2

### ISSUE THREAD

**Issue by KartoffelChipss** [DanikingRD/BackTools#16]
I am trying to use the mod in Minecraft 1.20.2 Fabric, but when starting the game, I just get an "Exit-Code: 1" error in the launcher.

I am using the latest version of BackTools, Fabric API (v0.90.7) and Cloth Config API (v12.0.111).

**Comment by venaminecraft** [comment]
Any update on this @DanikingRD?

**Comment by FireInstall** [comment]
Would 1.20.4 do the trick for you?
[unofficial](https://github.com/FireInstall/BackTools/releases/tag/1.20.4-0)

**Comment by venaminecraft** [comment]
Thank you @FireInstall.

I switched now to YDMs Weapon Master, but it's great to see that the mod is now available for the 1.20.4.

Good work!

**Comment by ldanidev** [comment]
I've just released the 1.20.4 version.  Maybe that'll work for you.

**Comment by ldanidev** [comment]
Closing this, as it seems to be working just fine.
