### ISSUE TITLE
Shields look gigantic

### ISSUE THREAD

**Issue by LidleVolkan** [DanikingRD/BackTools#18]
![2024-01-23_15 54 50](https://github.com/DanikingRD/BackTools/assets/157493201/9b8a2f42-5b0d-4b9a-a94a-ad12e9491577)
![2024-01-23_15 54 52](https://github.com/DanikingRD/BackTools/assets/157493201/7a4bb7d6-5e61-473d-be2a-0f5513a9091d)

Shields look like this in 1.20.1 😆 funny bug

**Comment by ldanidev** [comment]
This is fixed in #17. Thanks submitting the issue.
