### ISSUE TITLE
Confusion regarding config

### ISSUE THREAD

**Issue by Andre601** [DanikingRD/BackTools#3]
The readme seems to have a completely different format than what the mod itself is actually providing, making it a lot more confusing to configure the mod the way you want.

like, the default json5 created doesn't seem to have the same options. Also, even tho Cloth Config API seems required, is there no option it seems to open and configure settings ingame? Why the dependency when there is no ingame configuration?

**Comment by DanikingRD** [comment]
I know this is a very late response, but basically Cloth Config is not all about ingame configuration. Currently It's being used to create the config file that is generated (the json5 file). As for the confusion you have, feel free to further describe what problems were you facing if you still feel like it's very confusing.

**Comment by ldanidev** [comment]
> The readme seems to have a completely different format than what the mod itself is actually providing, making it a lot more confusing to configure the mod the way you want.
> 
> like, the default json5 created doesn't seem to have the same options. Also, even tho Cloth Config API seems required, is there no option it seems to open and configure settings ingame? Why the dependency when there is no ingame configuration?

I know this is a very late response, but basically Cloth Config is not all about ingame configuration. Currently It's being used to create the config file that is generated (the json5 file). As for the confusion you have, feel free to further describe what problems were you facing if you still feel like it's very confusing.

**Comment by FireInstall** [comment]
I guess they are talking about the config missing the disabling per type shown in the readme, but at the same time having new options:
config now
![config](https://github.com/DanikingRD/BackTools/assets/29309865/135f8215-6a10-423c-8d65-55a282addedd)
vs config in readme
![config](https://github.com/DanikingRD/BackTools/assets/29309865/e70075c5-b87b-4b1d-a8d9-fcff174fcfe3)

**Comment by ldanidev** [comment]
I'm closing this issue since I have already updated and explained how config file works in the README file. I apologize for any issues it might have caused.
