### ISSUE TITLE
Rendering alongside with capes

### ISSUE THREAD

**Issue by Scarlaid** [DanikingRD/BackTools#4]
I was wondering if items can be rendered behind capes, I mean I know this works for non-cape players but I do indeed like the idea of rendering it behind capes, like those fighting warriors irl ,or so

Maybe considerable? If not then I can understand that this could be impossible or hard to do, thanks :D

**Comment by ldanidev** [comment]
> I was wondering if items can be rendered behind capes, I mean I know this works for non-cape players but I do indeed like the idea of rendering it behind capes, like those fighting warriors irl ,or so
> 
> Maybe considerable? If not then I can understand that this could be impossible or hard to do, thanks :D

It could be an optional feature that you can enable in the config file. I would like you to explain it a little bit more though.
