### ISSUE TITLE
Tools spinning while swimming

### ISSUE THREAD

**Issue by ghost** [DanikingRD/BackTools#8]
As title says. Using the 1.20 version of the mod with cloth config and api installed and everything works normally otherwise, but when you swim underwater the tool on the back just spins. I tested the game with just those three mods (api, config, and backtools) so its not mod conflicts.

**Comment by DanikingRD** [comment]
It's not an issue, but rather an easter egg that the original mod had. Should probably add an option to disable it since I've seen other people complaining about it?

**Comment by ldanidev** [comment]
> As title says. Using the 1.20 version of the mod with cloth config and api installed and everything works normally otherwise, but when you swim underwater the tool on the back just spins. I tested the game with just those three mods (api, config, and backtools) so its not mod conflicts.

It's not an issue, but rather an easter egg that the original mod had. Should probably add an option to disable it since I've seen other people complaining about it?
